// Generated by CoffeeScript 1.9.2
(function() {
  var ordersByAthlete, ordersOfProtocol, searchIndexes, totalPublicProtocols;

  ordersByAthlete = function(doc) {
    if (doc._id.indexOf('order_athlete_') === 0) {
      return emit(doc.athlete, null);
    }
  };

  ordersOfProtocol = function(doc) {
    var id, protocol, ref, results;
    if (doc._id.indexOf('order_athlete_') === 0) {
      ref = doc.cart;
      results = [];
      for (id in ref) {
        protocol = ref[id];
        results.push(emit(id, protocol.qty));
      }
      return results;
    }
  };

  totalPublicProtocols = function(doc) {
    if (doc._id.indexOf('protocol_') === 0 && doc.title !== '' && doc.description !== '') {
      return emit('all', null);
    }
  };

  searchIndexes = function(doc) {
    var c, i, len, ref, results;
    if (doc._id.indexOf('protocol_') === 0 && doc.owner !== 'deleted') {
      index('public', doc.title !== '' && doc.description !== '' ? true : false);
      index('owner', doc.owner);
      index('length', doc.length);
      index('goal', doc.goal);
      index('experience', doc.experience);
      ref = doc.components;
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        c = ref[i];
        results.push(index('compound', c.compound.id));
      }
      return results;
    }
  };

}).call(this);
